package org.cognoseed.fitbit4s.model

class User(
  val aboutMe: String,
  val avatar: String,
  val avatar150: String,
  val city: String,
  val country: String,
  val dateOfBirth: String,
  val displayName: String,
  val distanceUnit: String,
  val encodedId: String,
  val foodsLocale: String,
  val fullName: String,
  val gender: String,
  val glucoseUnit: String,
  val height: Double,
  val heightUnit: String,
  val locale: String,
  val memberSince: String,
  val nickname: String,
  val offsetFromUTCMillis: Int,
  val state: String,
  val strideLengthRunning: Int,
  val strideLengthWalking: Int,
  val timezone: String,
  val waterUnit: String,
  val weight: Double,
  val weightUnit: String
)
